"""stream_issue_triage_and_auto_block_setting

Revision ID: 12bf74e53c8d
Revises: ce81034f5a5c
Create Date: 2026-03-22 22:48:56.889135

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12bf74e53c8d"
down_revision: Union[str, None] = "ce81034f5a5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contribution_settings",
        sa.Column(
            "auto_block_on_broken_reports",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column("stream_suggestions", sa.Column("issue_triage_status", sa.String(), nullable=True))
    op.add_column("stream_suggestions", sa.Column("issue_triage_note", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_stream_suggestions_issue_triage_status"), "stream_suggestions", ["issue_triage_status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stream_suggestions_issue_triage_status"), table_name="stream_suggestions")
    op.drop_column("stream_suggestions", "issue_triage_note")
    op.drop_column("stream_suggestions", "issue_triage_status")
    op.drop_column("contribution_settings", "auto_block_on_broken_reports")
    # ### end Alembic commands ###
