"""align cascade delete fk constraints

Revision ID: 24c9d2e84ae0
Revises: d4338ed0aa1a
Create Date: 2026-03-15 15:19:14.844034

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "24c9d2e84ae0"
down_revision: Union[str, None] = "d4338ed0aa1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("acestream_stream_stream_id_fkey"), "acestream_stream", type_="foreignkey")
    op.create_foreign_key(
        op.f("acestream_stream_stream_id_fkey"),
        "acestream_stream",
        "stream",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("external_link_stream_stream_id_fkey"), "external_link_stream", type_="foreignkey")
    op.create_foreign_key(
        op.f("external_link_stream_stream_id_fkey"),
        "external_link_stream",
        "stream",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("http_stream_stream_id_fkey"), "http_stream", type_="foreignkey")
    op.create_foreign_key(
        op.f("http_stream_stream_id_fkey"),
        "http_stream",
        "stream",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("media_image_media_id_fkey"), "media_image", type_="foreignkey")
    op.create_foreign_key(
        op.f("media_image_media_id_fkey"),
        "media_image",
        "media",
        ["media_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("media_rating_media_id_fkey"), "media_rating", type_="foreignkey")
    op.create_foreign_key(
        op.f("media_rating_media_id_fkey"),
        "media_rating",
        "media",
        ["media_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("mediafusion_rating_media_id_fkey"), "mediafusion_rating", type_="foreignkey")
    op.create_foreign_key(
        op.f("mediafusion_rating_media_id_fkey"),
        "mediafusion_rating",
        "media",
        ["media_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("telegram_stream_stream_id_fkey"), "telegram_stream", type_="foreignkey")
    op.create_foreign_key(
        op.f("telegram_stream_stream_id_fkey"),
        "telegram_stream",
        "stream",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("telegram_user_forward_telegram_stream_id_fkey"), "telegram_user_forward", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("telegram_user_forward_telegram_stream_id_fkey"),
        "telegram_user_forward",
        "telegram_stream",
        ["telegram_stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("torrent_stream_stream_id_fkey"), "torrent_stream", type_="foreignkey")
    op.create_foreign_key(
        op.f("torrent_stream_stream_id_fkey"),
        "torrent_stream",
        "stream",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("usenet_stream_stream_id_fkey"), "usenet_stream", type_="foreignkey")
    op.create_foreign_key(
        op.f("usenet_stream_stream_id_fkey"),
        "usenet_stream",
        "stream",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("youtube_stream_stream_id_fkey"), "youtube_stream", type_="foreignkey")
    op.create_foreign_key(
        op.f("youtube_stream_stream_id_fkey"),
        "youtube_stream",
        "stream",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("youtube_stream_stream_id_fkey"), "youtube_stream", type_="foreignkey")
    op.create_foreign_key(op.f("youtube_stream_stream_id_fkey"), "youtube_stream", "stream", ["stream_id"], ["id"])
    op.drop_constraint(op.f("usenet_stream_stream_id_fkey"), "usenet_stream", type_="foreignkey")
    op.create_foreign_key(op.f("usenet_stream_stream_id_fkey"), "usenet_stream", "stream", ["stream_id"], ["id"])
    op.drop_constraint(op.f("torrent_stream_stream_id_fkey"), "torrent_stream", type_="foreignkey")
    op.create_foreign_key(op.f("torrent_stream_stream_id_fkey"), "torrent_stream", "stream", ["stream_id"], ["id"])
    op.drop_constraint(
        op.f("telegram_user_forward_telegram_stream_id_fkey"),
        "telegram_user_forward",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("telegram_user_forward_telegram_stream_id_fkey"),
        "telegram_user_forward",
        "telegram_stream",
        ["telegram_stream_id"],
        ["id"],
    )
    op.drop_constraint(op.f("telegram_stream_stream_id_fkey"), "telegram_stream", type_="foreignkey")
    op.create_foreign_key(op.f("telegram_stream_stream_id_fkey"), "telegram_stream", "stream", ["stream_id"], ["id"])
    op.drop_constraint(op.f("mediafusion_rating_media_id_fkey"), "mediafusion_rating", type_="foreignkey")
    op.create_foreign_key(op.f("mediafusion_rating_media_id_fkey"), "mediafusion_rating", "media", ["media_id"], ["id"])
    op.drop_constraint(op.f("media_rating_media_id_fkey"), "media_rating", type_="foreignkey")
    op.create_foreign_key(op.f("media_rating_media_id_fkey"), "media_rating", "media", ["media_id"], ["id"])
    op.drop_constraint(op.f("media_image_media_id_fkey"), "media_image", type_="foreignkey")
    op.create_foreign_key(op.f("media_image_media_id_fkey"), "media_image", "media", ["media_id"], ["id"])
    op.drop_constraint(op.f("http_stream_stream_id_fkey"), "http_stream", type_="foreignkey")
    op.create_foreign_key(op.f("http_stream_stream_id_fkey"), "http_stream", "stream", ["stream_id"], ["id"])
    op.drop_constraint(op.f("external_link_stream_stream_id_fkey"), "external_link_stream", type_="foreignkey")
    op.create_foreign_key(
        op.f("external_link_stream_stream_id_fkey"), "external_link_stream", "stream", ["stream_id"], ["id"]
    )
    op.drop_constraint(op.f("acestream_stream_stream_id_fkey"), "acestream_stream", type_="foreignkey")
    op.create_foreign_key(op.f("acestream_stream_stream_id_fkey"), "acestream_stream", "stream", ["stream_id"], ["id"])
    # ### end Alembic commands ###
