"""add job queue tables

Revision ID: 61c656b49136
Revises: d2f1ac726426
Create Date: 2026-05-12 05:43:30.348943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61c656b49136'
down_revision: Union[str, None] = 'd2f1ac726426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_jobs',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.Column('queue', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_enqueued_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('job_events_job_id_idx', 'job_events', ['job_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('queue', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('priority', sa.SmallInteger(), server_default=sa.text('100'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='jobs_dedupe_key_uq')
    )
    op.create_index(op.f('ix_jobs_queue'), 'jobs', ['queue'], unique=False)
    op.create_index('jobs_claim_idx', 'jobs', ['queue', 'priority', 'scheduled_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('jobs_created_at_idx', 'jobs', ['created_at'], unique=False)
    op.create_index('jobs_running_idx', 'jobs', ['worker_id'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_index('jobs_status_finished_idx', 'jobs', ['status', 'finished_at'], unique=False)
    # ### end Alembic commands ###

    # NOTIFY trigger — wakes up QueueRunner instances on new pending jobs
    op.execute("""
        CREATE OR REPLACE FUNCTION jobs_notify_new() RETURNS trigger AS $$
        BEGIN
            IF NEW.status = 'pending' THEN
                PERFORM pg_notify('jobs_new_' || NEW.queue, NEW.id::text);
            END IF;
            RETURN NEW;
        END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER jobs_notify_new_tg
            AFTER INSERT ON jobs FOR EACH ROW EXECUTE FUNCTION jobs_notify_new();
    """)

    # Seed cron_jobs — mirrors schedules from the old Redis-Streams scheduler.
    # Disabled flags mirror config.rs defaults (disable_* = true → enabled = false).
    op.execute("""
        INSERT INTO cron_jobs (name, schedule, queue, payload, enabled) VALUES
        -- Non-Scrapy background tasks
        ('background_search',      '*/3 * * * *',  'background_search', '{}', true),
        ('prowlarr_feed',          '0 */3 * * *',  'prowlarr_feed',     '{}', true),
        ('jackett_feed',           '0 */3 * * *',  'jackett_feed',      '{}', true),
        ('rss_feed',               '0 */3 * * *',  'rss_feed',          '{}', true),
        ('dmm_hashlist',           '0 * * * *',    'dmm_hashlist',      '{}', true),
        ('youtube_bg',             '20 */6 * * *', 'youtube_bg',        '{}', false),
        ('acestream_bg',           '40 */6 * * *', 'acestream_bg',      '{}', true),
        ('telegram_bg',            '10 */6 * * *', 'telegram_bg',       '{}', false),
        ('validate_tv',            '0 0 * * 4',    'validate_tv',       '{}', true),
        ('update_seeders',         '0 0 * * 3',    'update_seeders',    '{}', false),
        ('update_tv_posters',      '0 2 * * *',    'update_tv_posters', '{}', true),
        ('discover_prewarm',       '0 4 * * *',    'discover_prewarm',  '{}', true),
        ('integration_syncs',      '0 */6 * * *',  'integration_syncs', '{}', true),
        ('cleanup_scraper_task',   '0 * * * *',    'cleanup', '{"task":"scraper_task"}', true),
        ('cleanup_cache',          '0 0 * * *',    'cleanup', '{"task":"cache"}',        true),
        -- Spider handlers (direct, non-registry)
        ('spider_tamilmv',         '0 */3 * * *',  'spider_tamilmv',        '{}', true),
        ('spider_tamil_blasters',  '0 */6 * * *',  'spider_tamil_blasters', '{}', true),
        ('spider_formula_ext',     '*/30 * * * *', 'spider_formula_ext',    '{}', true),
        ('spider_motogp_ext',      '0 5 * * *',    'spider_motogp_ext',     '{}', true),
        ('spider_wwe_ext',         '10 */3 * * *', 'spider_wwe_ext',        '{}', true),
        ('spider_ufc_ext',         '30 */3 * * *', 'spider_ufc_ext',        '{}', true),
        ('spider_movies_tv_ext',   '0 * * * *',    'spider_movies_tv_ext',  '{}', true),
        ('spider_sport_video',     '*/20 * * * *', 'spider_sport_video',    '{}', true),
        ('spider_eztv_rss',        '0 */2 * * *',  'spider_eztv_rss',       '{}', true),
        -- Registry-driven spiders (share the spider_registry_crawl queue, payload selects indexer)
        ('spider_registry_nyaa',        '15 */3 * * *', 'spider_registry_crawl', '{"indexer":"nyaa"}',         true),
        ('spider_registry_animetosho',  '30 */4 * * *', 'spider_registry_crawl', '{"indexer":"animetosho"}',   true),
        ('spider_registry_subsplease',  '45 */4 * * *', 'spider_registry_crawl', '{"indexer":"subsplease"}',   true),
        ('spider_registry_animepahe',   '0 */6 * * *',  'spider_registry_crawl', '{"indexer":"animepahe"}',    false),
        ('spider_registry_bt52',        '30 */6 * * *', 'spider_registry_crawl', '{"indexer":"bt52"}',         false),
        ('spider_registry_uindex',      '0 */4 * * *',  'spider_registry_crawl', '{"indexer":"uindex"}',       false),
        ('spider_registry_x1337',       '0 */6 * * *',  'spider_registry_crawl', '{"indexer":"x1337"}',        false),
        ('spider_registry_thepiratebay','30 */6 * * *', 'spider_registry_crawl', '{"indexer":"thepiratebay"}', false),
        ('spider_registry_rutor',       '45 */6 * * *', 'spider_registry_crawl', '{"indexer":"rutor"}',        false),
        ('spider_registry_limetorrents','0 */8 * * *',  'spider_registry_crawl', '{"indexer":"limetorrents"}', false),
        ('spider_registry_yts',         '0 */12 * * *', 'spider_registry_crawl', '{"indexer":"yts"}',          false),
        ('spider_registry_bt4g',        '15 */8 * * *', 'spider_registry_crawl', '{"indexer":"bt4g"}',         false)
        ON CONFLICT (name) DO NOTHING;
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS jobs_notify_new_tg ON jobs")
    op.execute("DROP FUNCTION IF EXISTS jobs_notify_new()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('jobs_status_finished_idx', table_name='jobs')
    op.drop_index('jobs_running_idx', table_name='jobs', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('jobs_created_at_idx', table_name='jobs')
    op.drop_index('jobs_claim_idx', table_name='jobs', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_jobs_queue'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('job_events_job_id_idx', table_name='job_events')
    op.drop_table('job_events')
    op.drop_table('cron_jobs')
    # ### end Alembic commands ###
