"""add_missing_series_episode_columns

Revision ID: 55db6bd4aab2
Revises: 8d55e5e54b6a
Create Date: 2025-12-21 07:46:21.753721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55db6bd4aab2'
down_revision: Union[str, None] = '8d55e5e54b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_base_metadata_custom_title_year_type'), table_name='base_metadata', postgresql_where="((id)::text ~~ 'mf%'::text)")
    op.drop_index(op.f('idx_episode_file_lookup'), table_name='episode_file')
    op.add_column('series_episode', sa.Column('overview', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('series_episode', sa.Column('released', sa.DateTime(timezone=True), nullable=True))
    op.add_column('series_episode', sa.Column('thumbnail', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('series_episode', 'is_poster_working')
    op.drop_column('series_episode', 'plot')
    op.drop_column('series_episode', 'poster')
    op.drop_column('series_episode', 'air_date')
    op.drop_column('series_episode', 'runtime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series_episode', sa.Column('runtime', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('series_episode', sa.Column('air_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('series_episode', sa.Column('poster', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('series_episode', sa.Column('plot', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('series_episode', sa.Column('is_poster_working', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('series_episode', 'thumbnail')
    op.drop_column('series_episode', 'released')
    op.drop_column('series_episode', 'overview')
    op.create_index(op.f('idx_episode_file_lookup'), 'episode_file', ['torrent_stream_id', 'season_number', 'episode_number'], unique=False)
    op.create_index(op.f('ix_base_metadata_custom_title_year_type'), 'base_metadata', ['title', 'year', 'type'], unique=True, postgresql_where="((id)::text ~~ 'mf%'::text)")
    # ### end Alembic commands ###
