"""add_is_stub_to_series_episode

Revision ID: 5633887f53ad
Revises: 32962aacd8dc
Create Date: 2025-12-21 17:35:28.899459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5633887f53ad'
down_revision: Union[str, None] = '32962aacd8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first
    op.add_column('series_episode', sa.Column('is_stub', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows (they're real episodes, not stubs)
    op.execute("UPDATE series_episode SET is_stub = FALSE WHERE is_stub IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('series_episode', 'is_stub', nullable=False)
    
    # Create the index
    op.create_index(op.f('ix_series_episode_is_stub'), 'series_episode', ['is_stub'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_episode_is_stub'), table_name='series_episode')
    op.drop_column('series_episode', 'is_stub')
    # ### end Alembic commands ###
