"""add_aka_title_unique_constraint

Revision ID: 64ab9417af09
Revises: 55db6bd4aab2
Create Date: 2025-12-21 08:00:26.379719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ab9417af09'
down_revision: Union[str, None] = '55db6bd4aab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'aka_title', ['media_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aka_title', type_='unique')
    # ### end Alembic commands ###
