"""setting up table

Revision ID: aa39e79bd3ec
Revises: 
Create Date: 2022-08-21 13:18:03.211618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa39e79bd3ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tamil_blaster_movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('poster', sa.String(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('tamilblaster_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('video_qualities', sa.PickleType(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('video_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tamil_blaster_movies')
    # ### end Alembic commands ###
