"""add title search index

Revision ID: bf75239e668e
Revises: c63392160ce7
Create Date: 2024-11-24 08:21:14.384259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf75239e668e'
down_revision: Union[str, None] = 'c63392160ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aka_title', sa.Column('title_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, title)", ), nullable=False))
    op.create_index('idx_aka_title_fts', 'aka_title', ['title_tsv'], unique=False, postgresql_using='gin')
    op.create_index('idx_aka_title_trgm', 'aka_title', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.add_column('base_metadata', sa.Column('title_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, title)", ), nullable=False))
    op.drop_index('idx_base_title_search', table_name='base_metadata', postgresql_using='gin')
    op.create_index('idx_base_title_fts', 'base_metadata', ['title_tsv'], unique=False, postgresql_using='gin')
    op.create_index('idx_base_title_trgm', 'base_metadata', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_base_title_trgm', table_name='base_metadata', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_base_title_fts', table_name='base_metadata', postgresql_using='gin')
    op.create_index('idx_base_title_search', 'base_metadata', ['title'], unique=False, postgresql_using='gin')
    op.drop_column('base_metadata', 'title_tsv')
    op.drop_index('idx_aka_title_trgm', table_name='aka_title', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_aka_title_fts', table_name='aka_title', postgresql_using='gin')
    op.drop_column('aka_title', 'title_tsv')
    # ### end Alembic commands ###
