"""align metadata fk ondelete

Revision ID: d4338ed0aa1a
Revises: a9592d543dd6
Create Date: 2026-03-08 01:23:24.617290

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d4338ed0aa1a"
down_revision: Union[str, None] = "a9592d543dd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("movie_metadata_media_id_fkey"), "movie_metadata", type_="foreignkey")
    op.create_foreign_key(
        op.f("movie_metadata_media_id_fkey"),
        "movie_metadata",
        "media",
        ["media_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("series_metadata_media_id_fkey"), "series_metadata", type_="foreignkey")
    op.create_foreign_key(
        op.f("series_metadata_media_id_fkey"),
        "series_metadata",
        "media",
        ["media_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("tv_metadata_media_id_fkey"), "tv_metadata", type_="foreignkey")
    op.create_foreign_key(
        op.f("tv_metadata_media_id_fkey"),
        "tv_metadata",
        "media",
        ["media_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tv_metadata_media_id_fkey"), "tv_metadata", type_="foreignkey")
    op.create_foreign_key(op.f("tv_metadata_media_id_fkey"), "tv_metadata", "media", ["media_id"], ["id"])
    op.drop_constraint(op.f("series_metadata_media_id_fkey"), "series_metadata", type_="foreignkey")
    op.create_foreign_key(op.f("series_metadata_media_id_fkey"), "series_metadata", "media", ["media_id"], ["id"])
    op.drop_constraint(op.f("movie_metadata_media_id_fkey"), "movie_metadata", type_="foreignkey")
    op.create_foreign_key(op.f("movie_metadata_media_id_fkey"), "movie_metadata", "media", ["media_id"], ["id"])
    # ### end Alembic commands ###
