CATALOG_ID_DATA = [
    "mediafusion_search_movies",
    "mediafusion_search_series",
    "tamil_hdrip",
    "tamil_tcrip",
    "tamil_dubbed",
    "tamil_series",
    "malayalam_tcrip",
    "malayalam_hdrip",
    "malayalam_dubbed",
    "malayalam_series",
    "telugu_tcrip",
    "telugu_hdrip",
    "telugu_dubbed",
    "telugu_series",
    "hindi_tcrip",
    "hindi_hdrip",
    "hindi_dubbed",
    "hindi_series",
    "kannada_tcrip",
    "kannada_hdrip",
    "kannada_dubbed",
    "kannada_series",
    "english_hdrip",
    "english_tcrip",
    "english_series",
]

CATALOG_NAME_DATA = [
    "MediaFusion Search Movies",
    "MediaFusion Search Series",
    "Tamil HD Movies",
    "Tamil TCRip/DVDScr/HDCAM Movies",
    "Tamil Dubbed Movies",
    "Tamil Series",
    "Malayalam TCRip/DVDScr/HDCAM Movies",
    "Malayalam HD Movies",
    "Malayalam Dubbed Movies",
    "Malayalam Series",
    "Telugu TCRip/DVDScr/HDCAM Movies",
    "Telugu HD Movies",
    "Telugu Dubbed Movies",
    "Telugu Series",
    "Hindi TCRip/DVDScr/HDCAM Movies",
    "Hindi HD Movies",
    "Hindi Dubbed Movies",
    "Hindi Series",
    "Kannada TCRip/DVDScr/HDCAM Movies",
    "Kannada HD Movies",
    "Kannada Dubbed Movies",
    "Kannada Series",
    "English HD Movies",
    "English TCRip/DVDScr/HDCAM Movies",
    "English Series",
]
